<a href="https://colab.research.google.com/github/ahoorarstmn/PyTorch_DL_FaraDars/blob/main/01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Imports

In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'1.10.0+cu111'

# **Tensor Initialisation**

## From data

* `torch.tensor()`

In [ ]:
data = [[1., 2.], [3., 4.]]
type(data)

list

In [ ]:
data_tensor = torch.tensor(data, dtype=torch.int32)
data_tensor
data_tensor.dtype

torch.int32

## From NumPy arrays

* `torch.from_numpy()`
* `torch.as_tensor()`


In [ ]:
data_array = np.array(data)
type(data_array)

numpy.ndarray

In [ ]:
# torch.from_numpy()

In [ ]:
a = torch.from_numpy(data_array)
a

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
# torch.as_tensor()

In [ ]:
b = torch.as_tensor(data_array)
b

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

## With random or constant values

* `torch.zeros()`
* `torch.ones()`
* `torch.eye()`
* `torch.rand()`
* `torch.randn()`
* `torch.randint()`
* `torch.rand_like()`
* `torch.randn_like()`
* `torch.randint_like()`
* `torch.empty()`
* `torch.diag()`

In [ ]:
# torch.zeros()

In [ ]:
zeros_tensor = torch.zeros(3, 4)
zeros_tensor.dtype


torch.float32

In [ ]:
# torch.ones()

In [ ]:
ones_tensor = torch.ones(3, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# torch.eye()

In [ ]:
eye_tensor = torch.eye(4, 4)
eye_tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
# torch.rand()

In [ ]:
rand_tensor = torch.rand(3, 3)
rand_tensor

tensor([[0.8927, 0.8129, 0.3055],
        [0.3651, 0.8940, 0.4104],
        [0.7037, 0.6539, 0.5441]])

In [ ]:
# torch.randn()

In [ ]:
randn_tensor = torch.randn(4, 4)
randn_tensor

tensor([[-1.4246, -1.4729, -0.0510,  0.8107],
        [-0.9973, -1.2214, -1.7285, -0.8095],
        [ 0.8030, -0.8063,  0.4947,  2.1513],
        [-0.3280,  0.5791,  1.5965, -2.0122]])

In [ ]:
# torch.randint()

In [ ]:
randint_tensor = torch.randint(1, 10, (4, 4))
randint_tensor

tensor([[9, 3, 2, 9],
        [5, 1, 6, 8],
        [7, 1, 6, 3],
        [9, 6, 4, 7]])

In [ ]:
# torch.rand_like()

In [ ]:
base = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

In [ ]:
base_tensor = torch.tensor(base, dtype=torch.float32)
base_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
randlike_tensor = torch.rand_like(base_tensor)
randlike_tensor

tensor([[0.9631, 0.1320, 0.2703],
        [0.4147, 0.6699, 0.2135],
        [0.2200, 0.0018, 0.2813]])

In [ ]:
# torch.randn_like()

In [ ]:
randn_like_tensor = torch.randn_like(base_tensor)
randn_like_tensor

tensor([[-1.0177,  0.0711,  0.9200],
        [-0.1230,  0.9117, -0.6306],
        [-0.9250, -0.7277, -0.6332]])

In [ ]:
# torch.randint_like()

In [ ]:
randint_like_tensor = torch.randint_like(base_tensor, 1, 10)
randint_like_tensor

tensor([[8., 7., 3.],
        [5., 5., 7.],
        [8., 1., 5.]])

In [ ]:
# torch.zeros_like()


In [ ]:
zeroslike_tensor = torch.zeros_like(base_tensor)

In [ ]:
# torch.ones_like()

In [ ]:
oneslike_tensor = torch.ones_like(base_tensor)
oneslike_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.empty()

In [ ]:
empty_tensor = torch.empty(4, 4)
empty_tensor

tensor([[-3.3795e-23,  3.0945e-41,  3.3631e-44,  0.0000e+00],
        [        nan,  1.3312e-43,  1.1578e+27,  1.1362e+30],
        [ 7.1547e+22,  4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22,  3.8149e+03,  4.1371e-41]])

In [ ]:
# torch.diag()

In [ ]:
a = torch.randn(3)

In [ ]:
a

tensor([ 0.3318, -0.6324, -0.1883])

In [ ]:
diag_tensor = torch.diag(a)
diag_tensor

tensor([[ 0.3318,  0.0000,  0.0000],
        [ 0.0000, -0.6324,  0.0000],
        [ 0.0000,  0.0000, -0.1883]])

## Creating tensors from ranges

* `torch.arange()`
* `torch.linspace()`





In [ ]:
# torch.arange(start, end, steps)

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
b = torch.arange(1, 5)
b

tensor([1, 2, 3, 4])

In [ ]:
c = torch.arange(1, 3, 0.5)
c

tensor([1.0000, 1.5000, 2.0000, 2.5000])

In [ ]:
# torch.linspace(start, end, steps)

In [ ]:
e = torch.linspace(3, 10, steps=5)
e

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

## Attributes

* `tensor.shape`>>(`tensor.size()`)
* `tensor.dtype`
* `tensor.device`

In [ ]:
my_tensor = torch.rand(3, 4)

In [ ]:
# tensor.shape

In [ ]:
print(f'Tensor shape is: {my_tensor.shape}')
print(f'Tensor size is: {my_tensor.size()}')

Tensor shape is: torch.Size([3, 4])
Tensor size is: torch.Size([3, 4])


In [ ]:
# tensor.dtype

In [ ]:
print(f'Tensor data type: {my_tensor.dtype}')

Tensor data type: torch.float32


In [ ]:
# tensor.device

In [ ]:
print(f'Tensor device: {my_tensor.device}')

Tensor device: cpu


In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cuda'

In [ ]:
my_tensor.to(device)

tensor([[0.6717, 0.1307, 0.3599, 0.3905],
        [0.9712, 0.6706, 0.8477, 0.6572],
        [0.8602, 0.5157, 0.3729, 0.8928]], device='cuda:0')

In [ ]:
!nvidia-smi

Sun Apr 17 09:19:30 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0    29W /  70W |   1322MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# **Operations**

## Indexing and Slicing

In [ ]:
tensor = torch.randint(1, 10, (4, 4))

In [ ]:
tensor

tensor([[5, 3, 6, 3],
        [1, 6, 9, 9],
        [1, 4, 2, 4],
        [7, 2, 7, 6]])

In [ ]:
print(f'First row: ', tensor[0])

First row:  tensor([5, 3, 6, 3])


In [ ]:
print(f'First Column: ', tensor[:, 0])

First Column:  tensor([5, 1, 1, 7])


In [ ]:
tensor[-1:, -1:]

tensor([[6]])

In [ ]:
tensor[:, 1] = 5

In [ ]:
tensor

tensor([[5, 5, 6, 3],
        [1, 5, 9, 9],
        [1, 5, 2, 4],
        [7, 5, 7, 6]])

## Joining tensors

* `torch.cat()` 
* `torch.stack()`

In [ ]:
a = torch.randint(1, 5, (4, 4))
b = torch.randint(5, 10, (4, 4))

In [ ]:
# torch.cat()

In [ ]:
cat_tensor = torch.cat((a, b), dim=0)

In [ ]:
cat_tensor

tensor([[4, 4, 4, 3],
        [1, 2, 2, 1],
        [4, 2, 4, 1],
        [3, 2, 4, 1],
        [8, 7, 8, 5],
        [7, 9, 9, 5],
        [7, 7, 6, 5],
        [8, 5, 6, 8]])

In [ ]:
# torch.stack()

In [ ]:
stack_tensor = torch.stack((a, b), dim=0)

In [ ]:
stack_tensor

tensor([[[4, 4, 4, 3],
         [1, 2, 2, 1],
         [4, 2, 4, 1],
         [3, 2, 4, 1]],

        [[8, 7, 8, 5],
         [7, 9, 9, 5],
         [7, 7, 6, 5],
         [8, 5, 6, 8]]])

## Reshaping a tensor
* `torch.view()` 
* `torch.reshape()`
* `torch.view_as()`

In [ ]:
x = torch.rand(16)

In [ ]:
# torch.view()

In [ ]:
y = x.view(4, 4)
y

tensor([[0.1250, 0.5114, 0.8498, 0.6031],
        [0.0823, 0.0168, 0.0919, 0.1436],
        [0.6534, 0.8182, 0.5274, 0.7185],
        [0.4340, 0.5611, 0.0851, 0.4738]])

In [ ]:
# torch.reshape()

In [ ]:
a = torch.arange(4)

In [ ]:
a

tensor([0, 1, 2, 3])

In [ ]:
torch.reshape(a, (2, 2))

tensor([[0, 1],
        [2, 3]])

In [ ]:
# torch.view_as()

## Arithmetic Operations


In [ ]:
tensor_a = torch.tensor([[1, 2], [1, 3]])
tensor_b = torch.tensor([[2, 3], [0, 4]])

In [ ]:
# Addition

In [ ]:
print(tensor_a + tensor_b)

tensor([[3, 5],
        [1, 7]])


In [ ]:
# Subtraction

In [ ]:
print(tensor_a - tensor_b)

tensor([[-1, -1],
        [ 1, -1]])


In [ ]:
# Multiplication

In [ ]:
print(tensor_a * tensor_b)

tensor([[ 2,  6],
        [ 0, 12]])


In [ ]:
# Division

In [ ]:
print(tensor_a / tensor_b)

tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])


In [ ]:
# Exponent

In [ ]:
print(tensor_a ** tensor_b)

tensor([[ 1,  8],
        [ 1, 81]])


In [ ]:
# Matrix Multiplication

In [ ]:
mytensor = torch.randint(1, 5, (4, 4))

In [ ]:
matrix_mul = mytensor @ mytensor.T

In [ ]:
print(matrix_mul)

tensor([[27, 31, 27, 22],
        [31, 45, 40, 26],
        [27, 40, 45, 27],
        [22, 26, 27, 22]])


In [ ]:
matrix_mul_new = mytensor.matmul(mytensor.T)
matrix_mul_new

tensor([[27, 31, 27, 22],
        [31, 45, 40, 26],
        [27, 40, 45, 27],
        [22, 26, 27, 22]])

## Single-element tensors

In [ ]:
# torch.item()

In [ ]:
mytensor

tensor([[4, 3, 1, 1],
        [4, 3, 4, 2],
        [2, 4, 3, 4],
        [2, 4, 1, 1]])

In [ ]:
agg = mytensor.sum()
agg

tensor(43)

In [ ]:
agg_item = agg.item()
print(agg_item, type(agg_item))

43 <class 'int'>


## In-place Operations






In [ ]:
x = torch.rand(1)
y = torch.rand(1)

In [ ]:
x, y

(tensor([0.2785]), tensor([0.2947]))

In [ ]:
# Noraml Addition

In [ ]:
x + y

tensor([0.5732])

In [ ]:
x

tensor([0.2785])

In [ ]:
# In-place Addition

In [ ]:
x.add_(y)

tensor([0.5732])

In [ ]:
x

tensor([0.5732])

## Other Operations



* Common Functions
* Trigonometric Functions
* Bitwise Operations
* Comparison Operations
* Reduction Operations
* Linear Algebra Operations


|| Some Useful Operations||
|:--- | :---: |  ---:  |
|`torch.max()`|`torch.norm()`|`torch.ndimension`|
|`torch.min()`|`torch.mean()`|`torch.remainder`|
|`torch.sum()`|`torch.eq()`|`torch.where()`|
|`torch.abs()`|`torch.clamp()`|`torch.numel()`|
|`torch.argmax()`|`torch.sort()`|`torch.clone()`|
|`torch.argmin()`|`torch.any()`|`torch.squeeze()`|
|`torch.sqrt()`|`torch.all()`|`torch.unsqueeze()`|
|`torch.exp()`|`torch.unique()`|`torch.t()`|


In [ ]:
a = torch.ones(2, 2)

In [ ]:
b = a

a[0][1] = 777

print(b)

tensor([[  1., 777.],
        [  1.,   1.]])


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

In [ ]:
assert b is not a
print(torch.eq(a, b))

tensor([[True, True],
        [True, True]])


In [ ]:
a[0][1] = 777
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

tensor([[0.9396, 0.3045],
        [0.1695, 0.2155]], requires_grad=True)


In [ ]:
b = a.clone()
print(b)

tensor([[0.9396, 0.3045],
        [0.1695, 0.2155]], grad_fn=<CloneBackward0>)


In [ ]:
c = a.detach().clone()
print(c)

tensor([[0.9396, 0.3045],
        [0.1695, 0.2155]])


In [ ]:
# 3 x 256 x 256 --> Image size

# N x 3 x 256 x 256 --> N is the Batch size

a = torch.rand(3, 256, 256)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 256, 256])
torch.Size([1, 3, 256, 256])


In [ ]:
c = torch.rand(1, 1, 1, 1, 1, 1)
print(c)

tensor([[[[[[0.9192]]]]]])


In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.1214, 0.0637, 0.7021, 0.7037, 0.9275, 0.2709, 0.4381, 0.0235, 0.1998,
         0.7676, 0.0161, 0.5531, 0.0544, 0.4693, 0.2151, 0.5421, 0.6956, 0.2522,
         0.9010, 0.9329]])


In [ ]:
b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([20])
tensor([0.1214, 0.0637, 0.7021, 0.7037, 0.9275, 0.2709, 0.4381, 0.0235, 0.1998,
        0.7676, 0.0161, 0.5531, 0.0544, 0.4693, 0.2151, 0.5421, 0.6956, 0.2522,
        0.9010, 0.9329])


# Interopreability

## NumPy array to tensor

In [ ]:
numpy_array = np.ones((2, 3))

In [ ]:
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
print(type(numpy_array), numpy_array.dtype)
print(type(pytorch_tensor), pytorch_tensor.dtype)

<class 'numpy.ndarray'> float64
<class 'torch.Tensor'> torch.float64


In [ ]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

tensor([[0.3919, 0.7407, 0.9717],
        [0.8726, 0.4670, 0.4441]])


In [ ]:
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

[[0.39187533 0.74065554 0.9716718 ]
 [0.8726039  0.4669969  0.44406956]]
