<a href="https://colab.research.google.com/github/ArstmN/Pytorch_DL_FaraDars/blob/main/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Autograd**

**Function:**

$$y = a^3 + b ^ 2 $$

**Partial Derivatives:**

$$\frac{∂ y}{\partial a} = 3a^2 = 3\times5^2 = 75$$

$$\frac{∂ y}{\partial b} = 2b = 2\times4 = 8$$

In [ ]:
import torch

In [ ]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([4.], requires_grad=True)

In [ ]:
y = a**3 + b**2

In [ ]:
y

tensor([141.], grad_fn=<AddBackward0>)

In [ ]:
print(a.grad, b.grad)

None None


In [ ]:
y.backward()

In [ ]:
print(a.grad, b.grad)

tensor([75.]) tensor([8.])


In [ ]:
w = torch.randn(10, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [ ]:
w

tensor([[-0.6327],
        [-0.6490],
        [-1.5569],
        [ 2.1182],
        [-0.5039],
        [ 1.0245],
        [ 0.6435],
        [-0.6796],
        [-0.3712],
        [-0.6019]], requires_grad=True)

In [ ]:
b

tensor([-0.9226], requires_grad=True)

In [ ]:
x = torch.rand(1, 10)

In [ ]:
result = torch.matmul(x, w) + b

In [ ]:
result

tensor([[-0.8530]], grad_fn=<AddBackward0>)

In [ ]:
loss = 1 - result

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor([[-0.6109],
        [-0.1966],
        [-0.2507],
        [-0.5022],
        [-0.2765],
        [-0.3159],
        [-0.6473],
        [-0.1267],
        [-0.0820],
        [-0.9535]])

In [ ]:
b.grad

tensor([-1.])

In [ ]:
with torch.no_grad():
    w = w - 0.001 * w.grad.data

In [ ]:
w

tensor([[-0.6321],
        [-0.6488],
        [-1.5566],
        [ 2.1187],
        [-0.5036],
        [ 1.0249],
        [ 0.6442],
        [-0.6794],
        [-0.3711],
        [-0.6010]])